webbr/urls.py
from django.conf.urls import url
from . import views

app_name = 'webbr'

urlpatterns = [
    url(r'^$', views.index, name="index"),
    url(r'^trending/$', views.trending, name="trending"),
    url(r'^(?P<topic_name>[a-z]+)/$', views.topic_index, name="topic_index"),
    url(r'^details/(?P<id>[0-9]+)/$', views.details, name="details"),
]

wproject/urls.py
from django.conf.urls import url, include
from django.contrib import admin


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('webbr.urls')),
]

webbr/models.py
from django.db import models
import datetime

topics = ['politics', 'movies', 'music']


class Topic(models.Model):
    topic = models.CharField(max_length=10, choices=[(name, name) for name in topics])
    keywords = models.CharField(max_length=50)
    display_name = models.CharField(max_length=30)

    def __str__(self):
        return self.display_name + ' - ' + self.topic


class Sentiment(models.Model):
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE)
    date = models.CharField(default=str(datetime.date.today()), max_length=10)
    value = models.FloatField(default=0)

    def __str__(self):
        return self.topic.display_name + ' ' + self.date


class Trending(models.Model):
    keyword = models.CharField(max_length=50)
    date = models.CharField(default=str(datetime.date.today()), max_length=10)
    value = models.FloatField(default=0)

    def __str__(self):
        return self.keyword + ' ' + self.date


class TrendingIndia(Trending):
    def __str__(self):
        return self.keyword + ' ' + self.date


class TrendingWorldwide(Trending):
    def __str__(self):
        return self.keyword + ' ' + self.date

webbr/views.py
from django.shortcuts import render, get_object_or_404, redirect
from webbr.models import Topic, TrendingWorldwide, TrendingIndia
from .models import topics
from django.http import HttpResponse


def index(request):
    return render(request, 'webbr/index.html', {'topics': topics})


def topic_index(request, topic_name):
    all_topic_obj = Topic.objects.filter(topic=topic_name)
    if len(all_topic_obj) == 0:
        return redirect('webbr:index')
    sent = all_topic_obj[0].sentiment_set.all().order_by('date')
    name = all_topic_obj[0].display_name
    context = {'sent': sent, 'name': name, 'all_topic_obj': all_topic_obj, 'topic_name': topic_name}
    return render(request, 'webbr/detail.html', context)


def details(request, id):
    topic_obj = get_object_or_404(Topic, pk=id)
    topic_name = topic_obj.topic
    all_topic_obj = Topic.objects.filter(topic=topic_name)
    if len(all_topic_obj) == 0:
        return redirect('webbr:index')
    sent = topic_obj.sentiment_set.all().order_by('date')
    name = topic_obj.display_name
    context = {'sent': sent, 'name': name, 'all_topic_obj': all_topic_obj, 'topic_name': topic_name}
    return render(request, 'webbr/detail.html', context)


def trending(request):
    trending_india = TrendingIndia.objects.all()
    trending_world = TrendingWorldwide.objects.all()
    context = {'trending_india': trending_india, 'trending_world': trending_world, 'topic_name': 'trending'}
    return render(request, 'webbr/trending.html', context)

webbr/templates/webbr/base.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Webbr{% endblock %}</title>
    {% load staticfiles %}
    <link href="https://fonts.googleapis.com/css?family=Raleway" rel="stylesheet">
    <link rel="stylesheet" href={% static 'webbr/css/fontawesome/css/font-awesome.min.css' %}>
    <link rel="stylesheet" href="{% static 'webbr/css/base.css' %}">
    {% block head %}{% endblock %}
</head>
<body>
<nav>
    <div class="logo">
        <a href="{% url 'webbr:index' %}">Webbr</a>
    </div>
    <div id="nav_menu">
        <i class="fa fa-bars" aria-hidden="true"></i>
    </div>
    <div id="navigation">
        <a href="{% url 'webbr:topic_index' 'movies' %}"
           {% if topic_name == 'movies' %}class="active"{% endif %}><strong><i class="fa fa-camera"
                                                                               aria-hidden="true"></i></strong><span>Movies</span></a>
        <a href="{% url 'webbr:topic_index' 'music' %}" {% if topic_name == 'music' %}class="active"{% endif %}><strong><i
                class="fa fa-music" aria-hidden="true"></i></strong><span>Music</span></a>
        <a href="{% url 'webbr:topic_index' 'politics' %}"
           {% if topic_name == 'politics' %}class="active"{% endif %}><strong><i class="fa fa-address-book"
                                                                                 aria-hidden="true"></i></strong><span>Politics</span></a>
        <a href="{% url 'webbr:trending' %}" {% if topic_name == 'trending' %}class="active"{% endif %}><strong><i
                class="fa fa-fire" aria-hidden="true"></i></strong><span>Trending</span></a>
    </div>
</nav>
<div class="clear"></div>
{% block body %}
{% endblock %}
<div class="clear"></div>
<footer>
    <span>© Webbr 2017</span>
    <a href="#">About</a>
</footer>
<script>
    var menu = document.getElementById('nav_menu');
    var navigation = document.getElementById('navigation');
    menu.addEventListener('click', function () {
        if (navigation.style.display == 'none') {
            navigation.style.display = 'block';
            menu.style.color = '#f5f5f5';
        } else {
            navigation.style.display = 'none';
            menu.style.color = '#bbb';
        }
    });
</script>
{% block scripts %}{% endblock %}
</body>
</html>

webbr/templates/webbr/detail.html
{% extends 'webbr/base.html' %}
{% block head %}
    {% load staticfiles %}
    <link rel="stylesheet" href="{% static 'webbr/css/details.css' %}">
{% endblock %}
{% block body %}
    <div class="wrapper" align="center">
        <div class="container-options">
            <table>
                <tr>
                    <th>Topic</th>
                </tr>
                {% for topic in all_topic_obj %}
                    <tr>
                        <td><a href="{% url 'webbr:details' topic.pk %}">{{ topic.display_name }}</a></td>
                    </tr>
                {% endfor %}
            </table>
        </div>
        <div id="data">
            {% for sentiment in sent %}
                <p class="hidden">{{ sentiment.date }} {{ sentiment.value }}</p>
            {% endfor %}
        </div>
        <p class="hidden" id="name">{{ name }}</p>
        <div class="container" id="container" align=center>
        </div>
    </div>
{% endblock %}
{% block scripts %}
    <script src="https://code.highcharts.com/highcharts.js"></script>
    <script src="https://code.highcharts.com/modules/exporting.js"></script>
    <script src="{% static 'webbr/js/details.js' %}"></script>
{% endblock %}

webbr/templates/webbr/index.html
{% extends 'webbr/base.html' %}
{% block head %}
    {% load staticfiles %}
    <link rel="stylesheet" href="{% static 'webbr/css/index.css' %}">
{% endblock %}
{% block body %}
    <div class="wrapper">
        <div class="container container-full" align=center>
            <a href="trending">
                <div class="thumbnail">
                    <img src="{% static 'webbr/images/oopTrending-2.jpg' %}" alt="Trending">
                </div>
            </a>
        </div>
        <div class="container container-thumbnail" align=center>
            <a href="politics">
                <div class="thumbnail">
                    <img src="{% static 'webbr/images/politics.jpg' %}" alt="Politics">
                </div>
                <div class="caption">
                    <h3>Politics</h3>
                </div>
            </a>
        </div>
        <div class="container container-thumbnail mid" align=center>
            <a href="music">
                <div class="thumbnail">
                    <img src="{% static 'webbr/images/music.jpg' %}" alt="Music">
                </div>
                <div class="caption">
                    <h3>Music</h3>
                </div>
            </a>
        </div>
        <div class="container container-thumbnail" align=center>
            <a href="movies">
                <div class="thumbnail">
                    <img src="{% static 'webbr/images/movies.jpg' %}" alt="Movies">
                </div>
                <div class="caption">
                    <h3>Movies</h3>
                </div>
            </a>
        </div>
    </div>
{% endblock %}

webbr/templates/webbr/trending.html
{% extends 'webbr/base.html' %}
{% block head %}
    {% load staticfiles %}
    <link rel="stylesheet" href="{% static 'webbr/css/trending.css' %}">
{% endblock %}
{% block body %}
    <div class="wrapper" align="center">
        <div class="container-options" align="center">
            <h2>Trending India</h2>
            <table>
                <tr>
                    <th>Topic</th>
                    <th>Sentiment</th>
                    <th>Date</th>
                </tr>
                {% for trending in trending_india %}
                    <tr>
                        <td>{{ trending.keyword }}</td>
                        <td>{{ trending.value }}</td>
                        <td>{{ trending.date }}</td>
                    </tr>
                {% endfor %}
            </table>
        </div>
        <div class="container-options" align="center">
            <h2>Trending Worldwide</h2>
            <table>
                <tr>
                    <th>Topic</th>
                    <th>Sentiment</th>
                    <th>Date</th>
                </tr>
                {% for trending in trending_world %}
                    <tr>
                        <td>{{ trending.keyword }}</td>
                        <td>{{ trending.value }}</td>
                        <td>{{ trending.date }}</td>
                    </tr>
                {% endfor %}
            </table>
        </div>
    </div>
{% endblock %}